### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by cjordan** [pkgw/rubbl#119]
According to https://github.com/casacore/casacore/blob/master/COPYING, casacore is licensed under the LGPL 2.  It appears that this changed on Nov 27, 2018, which was after rubbl's README declared casacore's license as GPL 2.

Are you happy to change rubbl's dual license to LGPL 2?  I'm interested mostly because I'm conscious of colleagues who may have issues using GPL code, thanks to their universities' policies, so this isn't a huge deal.  If you're happy for the change to happen, I can do it myself in a PR.

**Comment by pkgw** [comment]
Yes, LGPL2 is good. Thanks for being careful about these things!
