### ISSUE TITLE
Access table keywords with string types

### ISSUE THREAD

**Issue by cjordan** [pkgw/rubbl#147]
I have measurement sets with some string values I'd like to access.  Here's a screenshot of browsetable from within CASA (the last three rows in particular):

![2021-03-28-124115_438x657_scrot](https://user-images.githubusercontent.com/1513491/112742689-22318f00-8fc3-11eb-9fc1-d68aed623330.png)

Currently, `rubbl-casatables` only lists the keywords associated with Tables when calling `table_keyword_names`.  I was able to see some more info by augmenting `table_keyword_names` in `casatables/src/lib.rs`:

```
@@ -622,13 +622,16 @@ impl Table {
     pub fn table_keyword_names(&mut self) -> Result<Vec<String>, CasacoreError> {
         let mut result = Vec::new();
 
-        let rv = unsafe {
-            invoke_table_get_keyword_info(self.handle, &mut self.exc_info, |name, dtype| {
-                if dtype == glue::GlueDataType::TpTable {
-                    result.push(name);
-                }
-            })
-        };
+        let rv =
+            unsafe {
+                invoke_table_get_keyword_info(self.handle, &mut self.exc_info, |name, dtype| {
+                    match dtype {
+                        glue::GlueDataType::TpTable => result.push(name),
+                        glue::GlueDataType::TpString => result.push(name),
+                        _ => (),
+                    }
+                })
+            };
 
         if rv != 0 {
             return self.exc_info.as_err();
@@ -637,6 +640,15 @@ impl Table {
         Ok(result)
     }
```
 
Some Rust output from:
```
let table_keywords = main_table.table_keyword_names().unwrap();
dbg!(&table_keywords);
```
 
 ```
 [src/data_formats/ms/mod.rs:79] &table_keywords = [
    "ANTENNA",
    "DATA_DESCRIPTION",
    "FEED",
    "FLAG_CMD",
    "FIELD",
    "HISTORY",
    "OBSERVATION",
    "POINTING",
    "POLARIZATION",
    "PROCESSOR",
    "SPECTRAL_WINDOW",
    "STATE",
    "SOURCE",
    "QUALITY_KIND_NAME",
    "QUALITY_TIME_STATISTIC",
    "QUALITY_FREQUENCY_STATISTIC",
    "QUALITY_BASELINE_STATISTIC",
    "MWA_TILE_POINTING",
    "MWA_SUBBAND",
    "MWA_METADATA_VERSION",
    "MWA_MWAPY_VERSION",
    "MWA_COTTER_VERSION",
    "MWA_COTTER_VERSION_DATE",
]
```

Now, I don't know how to access the associated data.  I poked a couple of things but I'm pretty lost.  Any pointers?  I'd be happy to try and tackle this and submit a PR.

**Comment by pkgw** [comment]
Thanks for asking! First off, as a general statement, the support for keywords is *especially* half-baked — just enough to do what I needed for the rubbl-rxpackage spwglue tool.

It's certainly not super clear but the intent of the `table_keyword_names` function is to only return keywords associated with sub-tables — ie, the name is supposed to mean "names of (table keywords)", not "(keyword names) in a table". For your purposes, I could imagine a generic function `get_keyword_value` that got the value of a specific keyword, with a type parameter that runs through the usual rigamarole of verifying that the type of the data in the MS agrees with what the program expects.

As for how to get those values, you might check the implementation of `table_get_keyword_info` in `glue.cc`. The keyword data are loaded up through a `table.keywordSet()` call, which yields a `casacore::TableRecord` reference. With that reference you can pull out the data using the sorts of mechanisms that are already established in the glue layer.

Hope that helps, but happy to answer any more questions if/when they arise!

**Comment by cjordan** [comment]
Thanks! I'll investigate when I gather enough steam.

**Comment by derwentx** [comment]
This is done now, although to be honest the ergonomics aren't fantastic.

- Write table keywords: [`Table::put_keyword`](https://github.com/pkgw/rubbl/blob/0eaad37a0d35fb8eecb87dfa6aba30613efd7be9/casatables/src/lib.rs#L1351)
- Write column keyword: [`Table::put_column_keyword`](https://github.com/pkgw/rubbl/blob/0eaad37a0d35fb8eecb87dfa6aba30613efd7be9/casatables/src/lib.rs#L1420)
- read table keywords: [`Table::get_keyword_record`](https://github.com/pkgw/rubbl/blob/0eaad37a0d35fb8eecb87dfa6aba30613efd7be9/casatables/src/lib.rs#L1494) then [`TableRecord::get_field`](https://github.com/pkgw/rubbl/blob/0eaad37a0d35fb8eecb87dfa6aba30613efd7be9/casatables/src/lib.rs#L2335)
- read column keywords: [`Table::get_column_keyword_record`](https://github.com/pkgw/rubbl/blob/0eaad37a0d35fb8eecb87dfa6aba30613efd7be9/casatables/src/lib.rs#L1505) then [`TableRecord::get_field`](https://github.com/pkgw/rubbl/blob/0eaad37a0d35fb8eecb87dfa6aba30613efd7be9/casatables/src/lib.rs#L2335)

**Comment by cjordan** [comment]
```
use rubbl_casatables::{Table, TableOpenMode};

fn main() {
    let ms = std::env::args()
        .nth(1)
        .expect("No measurement set supplied");

    let mut t = Table::open(ms, TableOpenMode::Read).unwrap();
    let mut r = t.get_keyword_record().unwrap();
    let c: String = r.get_field("MWA_COTTER_VERSION").unwrap();
    dbg!(c);
    let c: String = r.get_field("MWA_METADATA_VERSION").unwrap();
    dbg!(c);
}
```

```
$ cargo run /data/chj/WORKING_DIR/MWA/1090008640/1090008640_4s_40kHz.ms
   Compiling test-rubbl-casatables v0.1.0 (/home/chj/Software/personal/test-rust/test-rubbl-casatables)
    Finished dev [unoptimized + debuginfo] target(s) in 2.27s
     Running `target/debug/test-rubbl-casatables /data/chj/WORKING_DIR/MWA/1090008640/1090008640_4s_40kHz.ms`
[src/main.rs:12] c = "4.5"
[src/main.rs:14] c = "2.0"
```

Looks good to me!  Thank you both so much!  It warms my heart to stay within Rust.
