### ISSUE TITLE
Handling of array shape mismatch could be more graceful.

### ISSUE THREAD

**Issue by derwentx** [pkgw/rubbl#165]
I had an issue trying to `put` a cell_value of shape `[4,2,1]` into a column of shape `[2,4,1]`, and it took forever to work out where the problem was because the error message wasn't super helpful.

```rust
let mut table = Table::open(&table_path, TableOpenMode::ReadWrite).unwrap();
let data_shape = [2, 4, 1];
table
    .add_array_column(
        "DATA",
        GlueDataType::TpComplex,
        // TODO: comment on dimensions
        None,
        Some(&data_shape),
        false,
        false,
    )
    .unwrap();

let cell_value = array![
    [[c64::new(1.0, 2.0)], [c64::new(-1.0, -2.0)]],
    [[c64::new(3.0, 4.0)], [c64::new(-3.0, -4.0)]],
    [[c64::new(5.0, 6.0)], [c64::new(-5.0, -6.0)]],
    [[c64::new(7.0, 8.0)], [c64::new(-7.0, -8.0)]]
];
table.put_cell("DATA", 0, &cell_value).unwrap();
```

The error is

` CasacoreError("Invalid Table data type when accessing column  in ArrayColumn ctor for column DATA")`

I'm opening this so that I can fix it later, once I'm done figuring out that segfault issue I'm having (my debugger is still playing up), and I keep forgetting to bring my old mac into work :P

**Comment by derwentx** [comment]
Ah, the actual problem with this code is the data type is `TpComplex`, which maps to `c32`, as opposed to `TpDComplex` <-> `c64` . The real error when sizes mismatch is 

```
CasacoreError("ArrayColumn::put for row 0 in column DATA: Table array conformance error")
```

Either way, it's difficult for new users to distinguish between these errors.

**Comment by derwentx** [comment]
Now that I think about it, I would understand if you wanted to close this and make it an upstream issue.

**Comment by pkgw** [comment]
Hm. In principle we could do our own checks and try to provide better error messages, but (1) we'd have to make sure that our checks and the lower-level checks agreed and (2) this could potentially add a non-trivial performance hit if we have to redundantly look up column/cell shape information. So I think I agree that this would best be solved upstream, although I have no idea how amenable they would be to changing these kinds of messages.

**Comment by derwentx** [comment]
Yeah, I agree. Might be more effort than it's worth if it involves touching casacore, so I'll just close this :P
