### ISSUE TITLE
`rubbl_casatables_impl` does not play nicely with dynamically linked casacore

### ISSUE THREAD

**Issue by derwentx** [pkgw/rubbl#177]
So the final hurdle I need to overcome is integrate rubbl into a library which depends on [aoflagger](https://gitlab.com/aroffringa/aoflagger), (a C++ library), which in turn dynamically links to system casacore. 

[Here's an example of what happens when you try to do this](https://github.com/derwentx/rubbl/tree/aoflagger)

```bash
cargo run --example aoflagger
```

```txt
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.16gq24j9fog1euvt.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.17pa5xmv3az8hq3g.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.1f5yonli7ukejw7a.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.1kgv2n5r190gpnsw.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.1lkxqrjba2xfjqsk.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.201eou91xu6cxmfz.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.23iwc8ya460o7p5i.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.247u5mhsjp75cyle.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.2dfmb8s85fgf31bv.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.2e2l0ukqy9nx9ehl.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.2e6qub8bm1vg13p.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.2joziq0hls5bh2gi.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.2otdyesvk4me15nh.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.321wnz0hbozpfigt.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.32iiy9l33y4g2swk.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.3900oz659edid5qo.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.3a96ute0ls60a53m.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.3euxygl2avtvn365.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.3h5uu0awzm8sulwv.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.42sc9o1k9vtv9j5k.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.45o41tn7z6499bf0.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.46rubjlz441yk1jp.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.4bwms4rodrcnguac.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.4cvk50yxv7r1qn5s.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.4g5rm1s91v7kigpi.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.4jewhwjrwmaobcnr.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.4msmtyriae1pdgak.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.4v7ix4w1wxtl300y.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.4vqeqn47p0mi9rz0.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.4y3yiqdl33juj4i2.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.4zpvze6d4a4c2z1a.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.526h85metrm87txt.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.5bpvcll37byiteua.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.8tscr8hn6nrc7vr.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.cf7mal42n678zuk.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.fhg5faix96dn6l3.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.mfabumz5pdiev6o.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.p1v1tkud1s94m6w.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.t24lxj1let3es2x.rcgu.o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9.4l7n8ep4eukhnoww.rcgu.o" "-Wl,--as-needed" "-L" "/home/ubuntu/rubbl/target/debug/deps" "-L" "/home/ubuntu/rubbl/target/debug/build/rubbl_casatables-03634f81c56c59eb/out" "-L" "/home/ubuntu/rubbl/target/debug/build/aoflagger_sys-eaa1edc3a138f823/out" "-L" "/home/ubuntu/rubbl/target/debug/build/cxx-7bcb08d8cdc2b483/out" "-L" "/home/ubuntu/rubbl/target/debug/build/link-cplusplus-c65b8acadc1dd30e/out" "-L" "/home/ubuntu/rubbl/target/debug/build/rubbl_casatables_impl-259c4b3eb238d806/out" "-L" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/ubuntu/rubbl/target/debug/deps/libaoflagger_sys-17a7e2441d33c252.rlib" "/home/ubuntu/rubbl/target/debug/deps/libcxx-fa5e1c8b53f53b74.rlib" "/home/ubuntu/rubbl/target/debug/deps/liblink_cplusplus-de8ee052f8c1a6d2.rlib" "/home/ubuntu/rubbl/target/debug/deps/librubbl_casatables-877bb02c726e0b5f.rlib" "/home/ubuntu/rubbl/target/debug/deps/librubbl_core-392e99bbdee78901.rlib" "/home/ubuntu/rubbl/target/debug/deps/libtermcolor-8f27c150af643511.rlib" "/home/ubuntu/rubbl/target/debug/deps/libbyteorder-f387c8e731df044c.rlib" "/home/ubuntu/rubbl/target/debug/deps/libapprox-dbdf745f86c8cf83.rlib" "/home/ubuntu/rubbl/target/debug/deps/libndarray-143b8cd2a5116d4a.rlib" "/home/ubuntu/rubbl/target/debug/deps/libmatrixmultiply-d39b18112f72a750.rlib" "/home/ubuntu/rubbl/target/debug/deps/libnum_complex-9acdff459ef95ba4.rlib" "/home/ubuntu/rubbl/target/debug/deps/libnum_integer-9f8a31d45bf1668f.rlib" "/home/ubuntu/rubbl/target/debug/deps/libnum_traits-fb574b6b6a0d3398.rlib" "/home/ubuntu/rubbl/target/debug/deps/librawpointer-6aa2ca10ed178081.rlib" "/home/ubuntu/rubbl/target/debug/deps/libfailure-fdb1d3c84a472728.rlib" "/home/ubuntu/rubbl/target/debug/deps/libbacktrace-ce06b6f72e2d0b71.rlib" "/home/ubuntu/rubbl/target/debug/deps/libminiz_oxide-c96737ccceaf4411.rlib" "/home/ubuntu/rubbl/target/debug/deps/libadler-005892d84f32fadf.rlib" "/home/ubuntu/rubbl/target/debug/deps/libobject-e8ea05f7d19f2c4e.rlib" "/home/ubuntu/rubbl/target/debug/deps/libaddr2line-cf893eb4714a5533.rlib" "/home/ubuntu/rubbl/target/debug/deps/libgimli-96bbd316763549a0.rlib" "/home/ubuntu/rubbl/target/debug/deps/libcfg_if-dece450273084492.rlib" "/home/ubuntu/rubbl/target/debug/deps/librustc_demangle-0cc08d6079258aff.rlib" "/home/ubuntu/rubbl/target/debug/deps/libclap-b1a1af300c325eed.rlib" "/home/ubuntu/rubbl/target/debug/deps/libvec_map-5f104c2ee05f26e6.rlib" "/home/ubuntu/rubbl/target/debug/deps/libtextwrap-349506f3b2349b3f.rlib" "/home/ubuntu/rubbl/target/debug/deps/libunicode_width-05a4b639dec6224c.rlib" "/home/ubuntu/rubbl/target/debug/deps/libstrsim-0fc606efc91e3789.rlib" "/home/ubuntu/rubbl/target/debug/deps/libbitflags-117d41ac256572da.rlib" "/home/ubuntu/rubbl/target/debug/deps/libatty-bc49c46593d1386b.rlib" "/home/ubuntu/rubbl/target/debug/deps/liblibc-c66dbc8ff67d320c.rlib" "/home/ubuntu/rubbl/target/debug/deps/libansi_term-329dab68dba20daf.rlib" "-Wl,--start-group" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-008055cc7d873802.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-06f01ac2578bda94.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-f9a3c3274a1835e0.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-d4cbb754ee9f4daa.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-95c14e1c1e3ebcc4.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-d489f0ca872880cc.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-75f07df0b18fea39.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-0c35b278736219a2.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-e530649c9a06e3c6.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-6b148909d375a785.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-cd15fa647f4775d1.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-74be3a703f788ba2.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-8f2c5b445c28b2e3.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-8480e85e0be96197.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-ac23a75f6f42004e.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-557ba8776e04d182.rlib" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-4beb03d03503c439.rlib" "-Wl,--end-group" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-dd7db1bec6909f24.rlib" "-Wl,-Bdynamic" "-laoflagger" "-lstdc++" "-lstdc++" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/ubuntu/rubbl/target/debug/examples/aoflagger-b459d9881107dbf9" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: /home/ubuntu/rubbl/target/debug/deps/librubbl_casatables-877bb02c726e0b5f.rlib(Aipsrc.o): undefined reference to symbol '_ZN8casacore6Aipsrc11findNoParseERNS_6StringERKS1_j'
          /usr/bin/ld: /lib/x86_64-linux-gnu/libcasa_casa.so.4: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

warning: `rubbl_casatables` (example "aoflagger") generated 2 warnings
error: could not compile `rubbl_casatables` due to previous error; 2 warnings emitted
```

I was wondering if you had any suggestions on how to approach this problem. I'm thinking that adding a feature which statically compiles rubbl_casatables_impl into rubbl_casatables would be a good way to do this, but I'm open to suggestions.

Cheers!

**Comment by pkgw** [comment]
Hmm, let's see. I think I understand where your suggestion is coming from: the first message is saying that there's an undefined reference in `librubbl_casatables`, which shouldn't happen, and then the next message seems to indicate that the linker *wants* to add symbols from `libcasa_casa`, but won't because it's not explicitly on the command line. So if the problem is that the `libcasa_casa` source of symbols is somehow preempting `librubbl_casatables_impl`, then I can see how what you suggest would fix the problem.

If there is indeed a way to implement your suggestion, I think that it would probably help. I am not sure if there is.

Alternatively one could rename all of the Rubbl CASA symbols to put them in a namespace like `rubblcasa`, and avoid the symbol conflicts entirely. I think this is probably the better solution since I suspect there will be a variety of other (toolchain-dependent) problems that might arise if one attempts to link an executable with both Rubbl casatables and the standard `libcasa_*`. I've thought about this before, but never got around to pursuing it. *Hopefully* a well-placed global `#define` would do the trick?

**Comment by derwentx** [comment]
Thanks for your thoughts on this! My understanding of linking is pretty basic, so it helps to have someone else's perspective.

I like your idea of just changing the namespace. it's a bit of added complexity when updating the latest casacore source within rubbl_casatables_impl, but it would completely get around this library confusion issue, I'm just a bit stumped on where the best place is for that global #define is, but I'll have a crack at it anyway.

The "undefined reference" in the first message might be referring to this, however I don't really know what conditions cause something to be undefined.

```txt
objdump -t /home/dev/rubbl/target/debug/build/rubbl_casatables_impl-1be5e8d779e4705f/out/casacore/casa/System/Aipsrc.o | grep '_ZN8casacore6Aipsrc11findNoParseERNS_6StringERKS1_j' -C 2
0000000000000000         *UND*  0000000000000000 __cxa_guard_abort
0000000000000000 g     F .text._ZN8casacore6Aipsrc7doParseERNS_6StringE 0000000000000370 _ZN8casacore6Aipsrc7doParseERNS_6StringE
0000000000000000         *UND*  0000000000000000 _ZN8casacore6Aipsrc11findNoParseERNS_6StringERKS1_j
0000000000000000         *UND*  0000000000000000 _ZNK8casacore4Time17modifiedJulianDayEv
0000000000000000 g     F .text._ZN8casacore6Aipsrc8genParseERNS_5BlockINS_6StringEEES4_RjRKS2_  0000000000000869 _ZN8casacore6Aipsrc8genParseERNS_5BlockINS_6StringEEES4_RjRKS2_
```

and yes, it seems to want to add symbols from system libcasa_casa, probably because it's a transitive dependency of aoflagger (the C++ library, not the whole example), and the symbol is definitely defined in that library.

```txt
objdump -T /usr/lib/libcasa_casa.so | grep Aipsrc11
00000000004387c0 g    DO .bss   0000000000000020  Base        _ZN8casacore6Aipsrc11extAipsPathE
0000000000311d80 g    DF .text  000000000000016f  Base        _ZN8casacore6Aipsrc11setAipsPathERKNS_6StringE
0000000000313130 g    DF .text  000000000000006b  Base        _ZN8casacore6Aipsrc11findNoParseERNS_6StringERKS1_j
```

Side note: Apparently the [`links`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key) key in cargo.toml is meant to prevent two rust libraries trying to link to the same system library, and there appears to be a way to bypass the build script if a package declares that it links to a specific library https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts . 

I'm wondering if I could use this to make it so that if a rust package is already linking to system casa, then we just use that and avoid casatables_impl/build.rs, then I can make aoflagger_sys declare that it `links` to both `aoflagger` and `casa`, and probably put some warnings in place to make sure people don't use incompatible versions of casacore. This actually sounds like the easiest way forward to me, but it's totally possible I'm misunderstanding how this all works.

**Comment by derwentx** [comment]
it seems like the `target.<triple>.<link>` thing does not prevent both libraries from having `links` to the same library, so it probably rules this idea out

**Comment by derwentx** [comment]
so apparently this is all that's needed. https://github.com/derwentx/rubbl/commit/0caa402cffaf294c44cc900832fc7b6130266183 

I find it very hard to believe that the solution is this simple, but it seems to be working. 

Will do some further tests and add a proper PR with more docco.

```bash
cargo run --example aoflagger /data/dev/1318943864_3C444/1318943864.corrected.ms
```

```txt
Table "/data/dev/1318943864_3C444/1318943864.corrected.ms":         
Number of rows: 132096                                              
Number of columns: 23                                               
aoflagger version: 3.1.0                                            
```

**Comment by pkgw** [comment]
Uh, yeah, a command-line #define could definitely do the trick! Everything in the casacore codebase is put in that one `casacore` namespace, so if you give it a new name, I believe you're good. My only concern would be if there were places where `casacore` showed up as an identifier with some other kind of usage, where the name of the identifier would matter (possible through, e.g. stringification in the preprocessor), but that seems super unlikely.

Anyway, regarding the use of system `libcasa_*` if available: I feel that this is not an option because I want to preserve the ability to alter the behavior of the `casatables_impl` C++ code relative to the standard casacore implementation. For instance, IIRC we do this right now by just stripping out a bunch of code that looks for user settings in `.aipsrc` files. That's a pretty minor change, but I could imagine cases where we really need to go in there with a screwdriver in order to get the Rust layer to behavior reliably. E.g., if the system library is not compiled with `-DUSE_THREADS`, it will be all sorts of bad news. With this constraint, we can't be sure that the framework will function if we link against system `libcasa_*`. It's frustrating because there's a lot of duplicate code in a use case like yours ... but CPU cycles are cheap and executables can get pretty large these days.

The other thing is that discovering and linking against the `libcasa_*` libraries is, in my experience, a pain, and their ABI stability is unclear. I think that it's a real quality-of-life improvement to just know that the `rubbl_casatables` library will build — and deployed executables will continue working — reliably, even if the use of system libraries were only optional.

I can think of one downside in your usecase. If you have an executable that links with both `rubbl_casatables` and system `libcasa_*`, there might be some internal, global state maintained by the casacore codebase that becomes split between the two different incarnations. If you try to do stuff with tables in both "worlds" at the same time, you might end up with problems similar to the ones we were seeing before we had `USE_THREADS=1`. *Hopefully* this won't arise in practice ...

**Comment by pkgw** [comment]
Also, hooray, *very* cool to see your program starting to work!

**Comment by derwentx** [comment]
The change seems to be holding up to my testing, it might be worth determining what parts of rubbl you think would be the most at risk of breaking from this change, and making sure they have adequate tests. Do you think you could throw your usual workload at #178 and see if you can break it? We could also put this change behind a non-default rust feature (any ideas what the name should be?)

**Comment by derwentx** [comment]
Awesome! If you could do another release, that would be great.

**Comment by pkgw** [comment]
This should now be available in the paired releases of `rubbl_casatables_impl` 0.3.31100 and `rubbl_casatables` 0.5.1. (The 0.5.0 release would have been fine, but there was an issue in the automated publication of the release to Crates.io.)
