### ISSUE TITLE
No support for adding MEASINFO record to column

### ISSUE THREAD

**Issue by derwentx** [pkgw/rubbl#180]
There are some features in casa which require specific metadata to be set in table columns for them to work. Here's an example of how the TableMeasDesc is set on the the REST_FREQUENCY column on the SOURCE table in [Cotter](https://github.com/MWATelescope/cotter/blob/b60b633b6b4b11bc5c84162bd0058a24d98f650c/mswriter.cpp#L126).

```c++
TableMeasRefDesc measRef(MFrequency::DEFAULT);
TableMeasValueDesc measVal(sourceTableDesc, MSSource::columnName(MSSourceEnums::REST_FREQUENCY));
TableMeasDesc<MFrequency> restFreqColMeas(measVal, measRef);
// write makes the Measure column persistent.
restFreqColMeas.write(sourceTableDesc);
```

Without this metadata in my Rubbl-generated measurement set, I get the following error in Casa plotms.

![image](https://user-images.githubusercontent.com/2578076/140475071-3f8d7468-723c-4f24-9a60-1290e168a75c.png)

I'll get start on this now :)

**Comment by pkgw** [comment]
Thank you for continuing to chip away at all of the problems you're running into!

For this case, I am wondering if our limited subset of casacore will provide all of the types necessary to attach the appropriate metadata :confused: Hopefully the measures metadata can be constructed simply without having to pull in a full dependency on UTC-TAI tables and whatnot ... Please let me know what you find!
